### ISSUE TITLE
what warn

### ISSUE THREAD

**Issue by blackvccat** [jenchanws/create-track-map#24] opened 2023-04-24 11:59 UTC
19:36:13] [TrackMap watcher/WARN] [createtrackmap/]: Exception during update loop

**Comment by jenchanws** [comment] 2023-04-24 20:35
Duplicate of #21. I already know about this issue; just give me a bit to write a fix.

**Closed as not planned by jenchanws** 2023-04-24 20:35 UTC

**Comment by blackvccat** [comment] 2023-04-25 02:07
very nice 謝謝



---Original---
From: "Jennifer Chan ***@***.***&gt;
Date: Tue, Apr 25, 2023 04:35 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jenchanws/create-track-map] what warn (Issue #24)




 
Closed #24 as not planned.
